### PR TITLE
fix(lex): parse `let f = (): RT<T>=>null;`

### LINKED ISSUE #1169: incorrect parse of '(): RT<T>=> { throw ''; }'
The following TypeScript code is parsed incorrectly by quick-lint-js:
```typescript
class RT<X> {}
class T {}

let f = (): RT<T>=> { throw ''; };
```

### PR DESCRIPTION
**Pull request by vegerot**
fix(lex): parse `let f = (): RT<T>=>null;`

Test Plan:
`let f = (): RT<T>=>null;`

Fixes #1169

### CODE REVIEW

File: src/quick-lint-js/fe/lex.cpp [hunk 1]
```diff
@@ -996,7 +996,12 @@ void Lexer::skip_less_less_as_less() {
 void Lexer::skip_as_greater() {
   switch (this->last_token_.type) {
   case Token_Type::greater_equal:
-    this->last_token_.type = Token_Type::equal;
+    if (this->input_[0] == '>') {
+      this->last_token_.type = Token_Type::equal_greater;
```
Comment (strager) [inline src/quick-lint-js/fe/lex.cpp:1000]: Nit: I think a comment would be helpful:
```suggestion
      // >=>  ➤  > =>
      this->last_token_.type = Token_Type::equal_greater;
```

Comment (strager) [inline src/quick-lint-js/fe/lex.cpp:1000]: Must fix: The `=>` token's .end is incorrect after this change. The following example demonstrates the bug:
```typescript
class C<T> {
  f(): C<T>=> {
  }
}
```

**Review by strager — CHANGES_REQUESTED** [review]

File: src/quick-lint-js/fe/lex.cpp (hunk 1 above)
Comment (vegerot) [reply src/quick-lint-js/fe/lex.cpp:1003]: Fixed.  What do you think?
